repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-ast
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: check-byte-order-marker
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.1
    hooks:
      - id: pycln
        files: "^(src|tests)/.*"
        args: [--all]
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: isort
        args: [--atomic, --profile=black, --multi-line=3]
        files: "^(src|tests)/.*"
        fail_fast: true
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        language_version: python3.10
        args: [--line-length=100, --skip-string-normalization]
        files: "^(src|tests)/.*"
        fail_fast: true
  - repo: https://github.com/dannysepler/rm_unneeded_f_str
    rev: v0.1.0
    hooks:
      - id: rm-unneeded-f-str
  - repo: local
      - id: pytest
        name: Run pytest
        stages: [commit, post-rewrite, manual]
        language: system
        entry: env FAIL_FAST=1 PYTEST_ADDOPTS="-k 'not e2e'" make test
        pass_filenames: false
        files: "^(^src\/|^tests\/)"
        fail_fast: true
      - id: test-dockerfile
        name: Testing production build
        stages: [commit]
        language: system
        entry: env FAIL_FAST=1 make test-docker
        pass_filenames: false
        files: (Pipfile|Pipfile\.lock|^docker\/)
        fail_fast: true
